config/routes.rb
Rails.application.routes.draw do
  root 'paiges#index'
  devise_for :users

  resources :paiges, path: "paiges", only: [:index, :show]

    namespace :api do
      namespace :v1 do
        resources :paiges, path: "paiges", only: [:index, :show]
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paige.rb
class Paige < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/paiges_controller.rb
class Api::V1::PaigesController < ApplicationController

    def index
      render json: Paige.all
    end

    def show
      render json: Paige.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paiges_controller.rb
class PaigesController < ApplicationController

    def index
      @paiges = Paige.all
    end

    def show
      @paige = Paige.find(params[:id])
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaigeMarie</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
</head>
<body>

  <nav class="top-bar">
    <% Paige.all.each do |paige| %>
        <% if paige.id === 6 %>
          <h2><%= link_to "The web-development", paige_path(paige.id) %></h2>
    <% end %>
    <% end %>

    <h2><a href="/">PaigeMarie</a></h2>


    <% Paige.all.each do |paige| %>
        <% if paige.id === 5 %>
          <h2><%= link_to "The music", paige_path(paige.id) %></h2>
    <% end %>
    <% end %>


    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>

app/views/paiges/show.html.erb
<div id="app">


</div>